### ISSUE TITLE
[fix] Rendering modal outside app route breaks server side rendering

### ISSUE THREAD

**Issue by lpsinger** [trussworks/react-uswds#1892]
**ReactUSWDS Version & USWDS Version:**

`@trussworks/react-uswds@2.7.1`, `uswds@2.13.1`

**Describe the bug**

#1890 broke Modal in apps and JavaScript frameworks that use server side rendering, because it relies on the `document` object, which only exists in the browser, not in the Node process that is doing the server side rendering. The error message is:

```
ReferenceError: document is not defined
    at Object.render (/.../my-remix-app/node_modules/@trussworks/react-uswds/lib/index.js:2:251331)
    at ReactDOMServerRenderer.render (/.../my-remix-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3872:44)
    at ReactDOMServerRenderer.read (/.../my-remix-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/.../my-remix-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at handleRequest (/.../my-remix-app/build/index.js:389:51)
    at renderDocumentRequest (/.../my-remix-app/node_modules/@remix-run/server-runtime/server.js:404:18)
    at async requestHandler (/.../my-remix-app/node_modules/@remix-run/server-runtime/server.js:55:20)
    at async /.../my-remix-app/node_modules/@remix-run/express/server.js:45:22
```

It is possible to work around by adding `renderToPortal={false}` to Modal components, but it does not work by default. Also this workaround will not solve the accessibility issues that #1890 addresses.

**To Reproduce**
```bash
git clone https://github.com/lpsinger/react-uswds-modal-ssr-bug-report.git
cd react-uswds-modal-ssr-bug-report
npm install
npm run dev
```

...then point a browser to http://localhost:3000

**Expected behavior**

The page should render and show a button that, when clicked, displays the Modal.

**Screenshots**

N/A

**Additional context**

This is a minimal reproducer from an app that uses server-side rendering that we are developing at NASA Goddard Space Flight Center.

**Device and Browser Information (please complete the following information if describing a UI bug):**

N/A

**Comment by acouch** [comment]
Adopting https://github.com/jesstelford/react-portal-universal would potentially allow server rendering, though would a heavy lift.

**Comment by mcmcgrath13** [comment]
I've been working around this by forcing it to only render on the client side. I have a little `ForceClient` component

```tsx
/**
 * Force a component to only render on the client side
 * @param params react params
 * @param params.loading component to show while loading
 * @param params.children component to render client side
 * @returns component
 */
export const ForceClient = ({
  children,
  loading,
}: {
  children: ReactNode;
  loading?: ReactNode;
}) => {
  const [render, setRender] = useState(false);

  useEffect(() => {
    setRender(true);
  }, []);

  return render ? <>{children}</> : <>{loading}</>;
};
```

then use it as
```tsx
<ModalTrigger />
<ForceClient>
   <Modal />
</ForceClient>
```

It's not ideal, but does seem to work okay as far as I can tell
