### ISSUE TITLE
[fix] Happo not running on PRs

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#2240]
**Describe the bug**

Happo is failing to run on all(?) PRs 

**To Reproduce**

1. Go to any PR
2. Click on failing build-and-test ci workflow
3. Scroll down to Happo
4. See error:
```
Run yarn happo-ci
yarn run v1.22.19
$ happo-ci-github-actions
fatal: ambiguous argument '9bd91379722aa010ed5a9ee2c90daa852ce4c922^': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Using the following ENV variables:
PREVIOUS_SHA: 9bd91379722aa010ed5a9ee2c90daa852ce4c922
CURRENT_SHA: e24708cb1b2be31e3f4365cf9c1f0e0b91eaa9d9
CHANGE_URL: https://github.com/trussworks/react-uswds/pull/2238
INSTALL_CMD: 
HAPPO_IS_ASYNC: true
HAPPO_SKIP_START_JOB: 
HAPPO_GIT_COMMAND: git
HAPPO_COMMAND: node_modules/happo.io/build/cli.js
HAPPO_FALLBACK_SHAS_COUNT: 50
Detected yarn.lock - using yarn to install dependencies
Failed POST https://happo.io/api/jobs/9bd91379722aa010ed5a9ee2c90daa852ce4c922/e24708cb1b2be31e3f4365cf9c1f0e0b91eaa9d9. Retrying...
Failed POST https://happo.io/api/jobs/9bd91379722aa010ed5a9ee2c90daa852ce4c922/e24708cb1b2be31e3f4365cf9c1f0e0b91eaa9d9. Retrying...
Failed POST https://happo.io/api/jobs/9bd91379722aa010ed5a9ee2c90daa852ce4c922/e24708cb1b2be31e3f4365cf9c1f0e0b91eaa9d9. Retrying...
Failed POST https://happo.io/api/jobs/9bd91379722aa010ed5a9ee2c90daa852ce4c922/e24708cb1b2be31e3f4365cf9c1f0e0b91eaa9d9. Retrying...
Failed POST https://happo.io/api/jobs/9bd91379722aa010ed5a9ee2c90daa852ce4c922/e24708cb1b2be31e3f4365cf9c1f0e0b91eaa9d9. Retrying...
Error: Request to POST https://happo.io/api/jobs/9bd91379722aa010ed5a9ee2c90daa852ce4c922/e24708cb1b2be31e3f4365cf9c1f0e0b91eaa9d9 failed: 401 - Unauthorized
    at retries (/home/runner/work/react-uswds/react-uswds/node_modules/happo.io/build/makeRequest.js:76:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Command.<anonymous> (/home/runner/work/react-uswds/react-uswds/node_modules/happo.io/build/executeCli.js:104:18)

/home/runner/work/react-uswds/react-uswds/node_modules/happo.io/build/makeRequest.js:76
        const e = new Error(`Request to ${method} ${url} failed: ${response.status} - ${await response.text()}`);
                  ^
Error: Request to POST https://happo.io/api/jobs/9bd91379722aa010ed5a9ee2c90daa852ce4c922/e24708cb1b2be31e3f4365cf9c1f0e0b91eaa9d9 failed: 401 - Unauthorized
    at retries (/home/runner/work/react-uswds/react-uswds/node_modules/happo.io/build/makeRequest.js:76:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Command.<anonymous> (/home/runner/work/react-uswds/react-uswds/node_modules/happo.io/build/executeCli.js:104:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Expected behavior**

Happo should run

**Additional context**

e.g. https://github.com/trussworks/react-uswds/actions/runs/4104875725/jobs/7080955015

**Comment by rpdelaney** [comment]
This seems to be fixed. Please re-open if I misunderstood!
